name: OpenEduHub - PR Deployment

on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'needs-rendering' || github.event_name == 'workflow_dispatch' }}
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set Deployment ID
        run: |
          # Use PR number for PR trigger and commit SHA for manual trigger
          if [[ -z "${{ github.event.pull_request.number }}" ]]; then
            echo "DEPLOYMENT_ID=trigger-${GITHUB_SHA::7}" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi
          echo "DEPLOYMENT_ID=${{ env.DEPLOYMENT_ID }}"

      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Build Jekyll site
        run: |
          # GitHub-specific config
          echo "url: https://${{ github.repository_owner }}.github.io" >> _config.yaml
          echo "baseurl: /operating-systems/${{ env.DEPLOYMENT_ID }}" >> _config.yaml

          # Build Docker image for Jekyll
          docker build -t jekyll-site .

          # Build Jekyll site
          docker run --rm \
            -v ${{ github.workspace }}:/usr/src/app/ \
            jekyll-site bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          destination_dir: ${{ env.DEPLOYMENT_ID }}
          publish_branch: gh-pages
          enable_jekyll: true

      - name: Add Comment to PR
        if: ${{ !startsWith(env.DEPLOYMENT_ID, 'trigger-') }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published at https://${{ github.repository_owner }}.github.io/operating-systems/${{ env.DEPLOYMENT_ID }}/

      - name: Output Deployment URL
        if: ${{ startsWith(env.DEPLOYMENT_ID, 'trigger-') }}
        run: |
          echo "The deployment is available at https://${{ github.repository_owner }}.github.io/operating-systems/${{ env.DEPLOYMENT_ID }}/"
